version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started
      - mvn install
  post_build:
    commands:
      - echo Packaging
      - mvn package
artifacts:
  files:
    - target/*.jar
    - appspec.yml
  discard-paths: yes