version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo "Build started"
      - mvn clean install
  post_build:
    commands:
      - echo "Packaging..."
      - mvn package
artifacts:
  files:
    - target/ERSProject-0.0.1-SNAPSHOT.jar