version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
  build:
    commands:
      - echo "Build started"
      - - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Finishing build..."
      - mv target/deployment ./
artifacts:
  files:
    - deployment/**/*