spring:
  application:
    name: ERSProject
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${ERS_DB_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ers
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
server:
  port:
    8080